version: '2'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.volumes/nginx-html:/usr/share/nginx/html
      - ./.volumes/nginx-conf:/etc/nginx/conf.d
      - ./.volumes/nginx-vhost:/etc/nginx/vhost.d
      - ./.volumes/nginx-certs:/etc/nginx/certs:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true

  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - ./.volumes/nginx-html:/usr/share/nginx/html
      - ./.volumes/nginx-conf:/etc/nginx/conf.d
      - ./.volumes/nginx-vhost:/etc/nginx/vhost.d
      - ./.volumes/nginx-certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    volumes:
      - ./.volumes/nginx-html:/usr/share/nginx/html
      - ./.volumes/nginx-conf:/etc/nginx/conf.d
      - ./.volumes/nginx-vhost:/etc/nginx/vhost.d
      - ./.volumes/nginx-certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  default:
    external:
      name: nginx-proxy
